# Generated by Django 3.2.12 on 2022-03-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    def initial_create_group_migration(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        Group.objects.bulk_create([
            Group(name=u'Admin'),
            Group(name=u'Guest'),
        ])

    def initial_revert_group_migration(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        Group.objects.filter(
            name__in=[
                u'Admin',
                u'Guest',
            ]
        ).delete()


    operations = [
        migrations.RunPython(initial_create_group_migration, initial_revert_group_migration)
    ]