# Generated by Django 3.2.12 on 2022-03-06 11:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  def segment_group_permission_migration(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    ContentType = apps.get_model("contenttypes", "ContentType")
    Segment = apps.get_model("montrafic", "Segment")
    content_type = ContentType.objects.get_for_model(Segment)


    view_segment,_ = Permission.objects.get_or_create(codename='view_segment', content_type=content_type)
    delete_segment,_ = Permission.objects.get_or_create(codename='delete_segment', content_type=content_type)
    change_segment,_ = Permission.objects.get_or_create(codename='change_segment', content_type=content_type)
    add_segment,_ = Permission.objects.get_or_create(codename='add_segment', content_type=content_type)

    guest_group = Group.objects.get(name='Guest')
    guest_group.permissions.add(view_segment)

    admin_group = Group.objects.get(name='Admin')
    admin_group.permissions.add(view_segment, delete_segment,
                                change_segment, add_segment)

  def segment_revert_group_permission_migration(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    view_segment = Permission.objects.get(codename="view_segment")
    delete_segment = Permission.objects.get(codename="delete_segment")
    change_segment = Permission.objects.get(codename="change_segment")
    add_segment = Permission.objects.get(codename="add_segment")


    guest_group = Group.objects.get(name='Guest')
    guest_group.permissions.remove(view_segment)

    admin_group = Group.objects.get(name='Admin')
    admin_group.permissions.remove(view_segment, delete_segment,
                                   change_segment,
                                   add_segment)


  dependencies = [
    ('montrafic', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='Segment',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID')),
        (
        'longitude', django.contrib.gis.db.models.fields.PointField(srid=4326)),
        ('latitude', django.contrib.gis.db.models.fields.PointField(srid=4326)),
        ('length', models.DecimalField(decimal_places=9, max_digits=15)),
        ('speed', models.DecimalField(decimal_places=12, max_digits=15)),
      ],
    ),

    migrations.RunPython(segment_group_permission_migration,
                         segment_revert_group_permission_migration)

  ]
