# Generated by Django 3.2.12 on 2022-03-06 23:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    def segment_group_permission_migration(apps, schema_editor):
        Permission = apps.get_model('auth', 'Permission')
        Group = apps.get_model('auth', 'Group')

        ContentType = apps.get_model("contenttypes", "ContentType")
        model_segment = apps.get_model("montrafic", "Segment")
        content_type_segment = ContentType.objects.get_for_model(model_segment)
        model_speed = apps.get_model("montrafic", "Speed")
        content_type_speed = ContentType.objects.get_for_model(model_speed)

        view_segment, _ = Permission.objects.get_or_create(
            codename='view_segment', content_type=content_type_segment)
        delete_segment, _ = Permission.objects.get_or_create(
            codename='delete_segment', content_type=content_type_segment)
        change_segment, _ = Permission.objects.get_or_create(
            codename='change_segment', content_type=content_type_segment)
        add_segment, _ = Permission.objects.get_or_create(
            codename='add_segment', content_type=content_type_segment)

        view_speed, _ = Permission.objects.get_or_create(
            codename='view_speed', content_type=content_type_speed)
        delete_speed, _ = Permission.objects.get_or_create(
            codename='delete_speed', content_type=content_type_speed)
        change_speed, _ = Permission.objects.get_or_create(
            codename='change_speed', content_type=content_type_speed)
        add_speed, _ = Permission.objects.get_or_create(
            codename='add_speed', content_type=content_type_speed)



        guest_group = Group.objects.get(name='Guest')
        guest_group.permissions.add(view_segment, view_speed)

        admin_group = Group.objects.get(name='Admin')
        admin_group.permissions.add(view_segment, delete_segment,
                                    change_segment, add_segment,
                                    view_speed, delete_speed, change_speed,
                                    add_speed)


    def segment_revert_group_permission_migration(apps, schema_editor):
        Permission = apps.get_model('auth', 'Permission')
        Group = apps.get_model('auth', 'Group')

        view_segment = Permission.objects.get(codename="view_segment")
        delete_segment = Permission.objects.get(codename="delete_segment")
        change_segment = Permission.objects.get(codename="change_segment")
        add_segment = Permission.objects.get(codename="add_segment")
        view_speed = Permission.objects.get(codename="view_speed")
        delete_speed = Permission.objects.get(codename="delete_speed")
        change_speed = Permission.objects.get(codename="change_speed")
        add_speed = Permission.objects.get(codename="add_speed")

        guest_group = Group.objects.get(name='Guest')
        guest_group.permissions.remove(view_segment, view_spped)

        admin_group = Group.objects.get(name='Admin')
        admin_group.permissions.remove(view_segment, delete_segment,
                                    change_segment, add_segment,
                                    view_speed, delete_speed, change_speed,
                                    add_speed)

    dependencies = [
        ('montrafic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('latitude', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('length', models.DecimalField(decimal_places=9, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.DecimalField(decimal_places=12, max_digits=15)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segment_speed', to='montrafic.segment')),
            ],
        ),

        migrations.RunPython(segment_group_permission_migration,
                             segment_revert_group_permission_migration)

    ]
