version: "3.0"
services:
  # Deploy PostgreSQL with Postgis db
  database_montraficdb_dev:
    image: postgis/postgis:12-master
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=montraficdb_dev
      - POSTGRES_USER=montraficdbuser
      - POSTGRES_PASSWORD:montraficdbpassword
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - .:/dev/data/db