version: "3.0"

services:
  # Deploy Django webserver in developement mode
  web:
    build:
      context: .
      dockerfile: infrastructure/web.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 --settings=ubiwhere_challenge.settings.production
    volumes:
      - .:/montrafic
    ports:
      - "80:8000"
    depends_on:
      - database_montraficdb


  # Deploy PostgreSQL with Postgis db
  database_montraficdb:
    image: postgis/postgis:12-master
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=montraficdb
      - POSTGRES_USER=montraficdbuser
      - POSTGRES_PASSWORD:montraficdbpassword
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - .:/prod/data/db